version: '3.9'
services:
  service:
    build: .
    ports:
      - 3000:3000
    depends_on:
      - postgres
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: m111
    ports:
      - 5432:5432
